# 单位信息配置文件
# 用于配置网站的基本信息、品牌信息等

# 组织信息
organization:
  name: "智能体知识库平台"           # 完整组织名称
  logo: "/favicon.svg"       # Logo文件路径（放在 web/public 目录下）
  avatar: "/avatar.jpg"      # 头像文件路径（放在 web/public 目录下）
  login_bg: "/login-bg.jpg"  # 登录背景图片路径（放在 web/public 目录下）

# 项目信息
branding:
  name: "GraphKnow"
  title: "GraphKnow: 更智能的知识库智能体平台"     # 系统标题
  # subtitle: "大模型驱动的知识库智能体平台"          # 副标题

features:



actions:
  # - name: "Test1"
  #   icon: "video"
  #   url: "https://www.test.com/video"
  # - name: "Test2"
  #   icon: "docs"
  #   url: "https://www.test.com/XXXXXX/"
  # - name: "Test3"
  #   icon: "issue"
  #   url: "https://www.test.com/XXXXXX/"
  # - name: "Test4"
  #   icon: "roadmap"
  #   url: "https://www.test.com/XXXXXXX/"



# 页脚信息
footer:
  copyright: "© 江南语析 2026 v0.5.0"
